version: "3.9"
services:
  pgdb:
    container_name: "home_library_pgdb"
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/pgdata
    env_file:
      - env.d/local-dev.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
  api:
    container_name: "home_library_api"
    build:
      context: .
      dockerfile: "api/Dockerfile"
    env_file:
      - env.d/local-dev.env
    environment:
      ENV_FILE: "/opt/home-library/env.d/local-dev.env"
    entrypoint: /opt/home-library/scripts/local-dev/server-entrypoint.sh
    volumes:
      - ".:/opt/local-dev"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
        - pgdb
